# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cefb9dcf5daf621fcc5bc22f79b88a6984c09cc5416b46bc46a10d39f3d014db320f5055fbfffcde6fe5500cd2be491c9f4c17a8b10819ab6108e8b6b6a0ccba

test:
  secret_key_base: 71a594e1a268c48d955bda7003c997dd8b9cdb2ffee23639a605ff8028ec5897a4c17c4eaec1d96b5cf005c8629b70bf1f94ecb996718076c9439c8f1016a19f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
